### ISSUE TITLE
Can you provide more commit information？

### ISSUE THREAD

**Issue by AmosChenYQ** [alibaba/TePDist#3]
I am very grateful to open source the internal work, but as an external user, I would like to see the details of the commit, so as to know which files have been changed/added

**Comment by lowintelligence** [comment]
Thank you @AmosChenYQ for the question. 
We have to squash our internal commits into one when open source the work due to some policies.
However, we also provided the original TF version the repo based as an submodule of the repo. You could just run 'git submodule update --init' after cloning the project, the base TF code would be downloaded into 'tf_community' directory. Then you can use some comparing tools or simply run 'diff -r' to examine the code changes.
